[package]
name = "draft"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = {version = "~1.17", default-features = false, features = [
"compat-1-2",
"unstable-wgpu-29",
"renderer-femtovg-wgpu",
"backend-winit-wayland", # NOTE: minimal features for (hopefully) better compile times
"live-preview"
]}
derive_more = "2.1"

vello = "0.10"
parley = "0.11"
static_assertions = "1"
thiserror = "2"
approx =  "0.5.1"
approx-derive = "0.2.8"

[build-dependencies]
slint-build = "1.17"

[profile.release]
codegen-units = 1
lto = true
