import { Button, VerticalBox, LineEdit } from "std-widgets.slint";
import { EditObject } from "edit.slint";
import { PopupMenu, PopupMenuButton } from "popup_menu.slint";

import {
    ObjectDataResponse,
    ObjectData,
    ObjectKind,
    TaggedObjectId,
    HoverInfo,
    ObjectDataUpdate,
    ToolData,
    WorldPos,
    Fmt,
} from "interop.slint";

component HRule {
    in property <color> color: #5c5c5c;
    in property <length> line_width: 1px;
    in property <length> pad_top_bottom: 4px;
    height: line_width + 2 * pad_top_bottom;
    width: 100%;

    HorizontalLayout {
        alignment: center;
        padding-top: root.pad_top_bottom;
        padding-bottom: root.pad_top_bottom;

        Rectangle {
            width: 100%;
            height: 100%;
            background: root.color;
        }
    }
}


export component MainWindow inherits Window {
    callback pointer_event(kind: PointerEventKind, button: PointerEventButton, x: float, y: float, modifiers: KeyboardModifiers);
    callback tool_choice(idx: int);
    callback delete_object(id: TaggedObjectId);
    callback update_object(update: ObjectDataUpdate);

    callback canvas_size_changed(w: float, h: float);

    in-out property <TaggedObjectId> hover_id;

    // INFO: it is important that hover_info.is_some == false for the "zero value" of the type HoverInfo
    in property <HoverInfo> hover_info;

    in property <ObjectDataResponse> selected_data;
    in property <HoverInfo> selected_info;

    property <float> scale_val: 1;

    in property <[ToolData]> tools;
    in property <int> selected_tool: -1;

    in-out property <bool> rcm_visible: false;
    in-out property <length> rcm_x;
    in-out property <length> rcm_y;

    in-out property <image> canvas;

    in property <bool> panning;
    in property <WorldPos> world_pos;

    preferred-width: 1200px;
    preferred-height: 800px;

    pure function fmt_float(f: float) -> float {
        (f * 100).round() / 100
    }

    function current_cursor() -> MouseCursor {
        if panning {
            return MouseCursor.grabbing;
        } else if hover_info.can-interact {
            return MouseCursor.pointer;
        } else {
            return MouseCursor.default;
        }
    }

    function show_rcm(id: TaggedObjectId, mouse_x: length, mouse_y: length) {
        root.rcm_x = mouse_x;
        root.rcm_y = mouse_y;
        rcm.show()
    }
    forward-focus: foc;

    foc := FocusScope {
        KeyBinding {
            keys: @keys(Escape);
            activated => { root.tool_choice(-1) };
        }

        VerticalLayout {

            HorizontalLayout {
                spacing: 4px;
                padding: 4px;
                height: 36px;
                for tool[i] in tools: Button {
                    text: tool.name;
                    checked: i == root.selected_tool ? true : false;
                    clicked => {
                        root.tool_choice(i == root.selected_tool ? -1 : i);
                    }
                }

                Rectangle { }
            }

            HorizontalLayout {

                Rectangle {
                    rcm := PopupWindow {
                        close-policy: close-on-click-outside;

                        // NOTE: when using a border radius and enabling content clipping on the rectangle,
                        // the contents appear blurred, which was fixed by rounding the positioning
                        // not sure when exactly this blurring can happen, but this is probably a good trick to remember

                        x: round(root.rcm_x / 1px) * 1px;
                        y: round(root.rcm_y / 1px) * 1px;

                        FocusScope {
                            KeyBinding {
                                keys: @keys(Escape);
                                activated => { rcm.close() }
                            }
                        }

                        PopupMenu {
                            PopupMenuButton {
                                label: "Edit";
                            }

                            PopupMenuButton {
                                label: "Delete";
                                enabled: root.hover_info.can-delete;
                                clicked => {
                                    rcm.close();
                                    root.delete_object(root.hover_info.id);
                                }
                            }

                            HRule { }

                            PopupMenuButton {
                                label: "Cancel";
                                clicked => { rcm.close() }
                            }
                        }
                    }

                    canvas := Image {
                        image-fit: fill;
                        width: 100%;
                        height: 100%;

                        changed width => {
                            root.canvas_size_changed(canvas.width / 1px,canvas.height / 1px)
                        }
                        changed height => {
                            root.canvas_size_changed(canvas.width / 1px,canvas.height / 1px)
                        }

                        source: root.canvas;
                        touch := TouchArea {
                            mouse-cursor: root.current_cursor();

                            pointer-event(event) => {
                                root.pointer_event(event.kind, event.button, self.mouse_x / 1px, self.mouse_y / 1px, event.modifiers);
                                if (event.kind == PointerEventKind.down && event.button == PointerEventButton.right) {
                                    if root.hover_info.is_some {
                                        root.show_rcm(root.hover_info.id, self.mouse_x, self.mouse_y)
                                    }
                                }
                                ;
                            }
                        }
                    }
                }

                VerticalLayout {
                    width: 300px;
                    alignment: start;
                    spacing: 8px;
                    padding: 8px;
                    cross-axis-alignment: start;

                    HRule { }

                    if (root.selected_data.ok): EditObject {
                        id: root.selected_data.id;
                        data: root.selected_data.data;
                        submit(id, data) => {
                            debug("submitting data for", id.raw);
                            root.update_object({ id: id, data: data })
                        }
                    }

                    if (!root.selected_data.ok): Rectangle {
                        Text {
                            text: "nothing selected";
                            color: gray;
                        }
                    }

                    if (root.selected_data.err != ""): Rectangle {
                        Text {
                            text: root.selected_data.err;
                            color: red;
                        }
                    }

                    HRule { }
                }
            }

            Rectangle {
                height: 40px;
                HorizontalLayout {
                    alignment: space-between;
                    padding: 8px;
                    spacing: 8px;

                    Text {
                        text: "(\{fmt_float(root.world_pos.x)}, \{fmt_float(root.world_pos.y)})";
                        horizontal-alignment: left;
                    }

                    Text {
                        text: root.hover_info.is-some ? "\{root.hover_info.id.raw} \{Fmt.fmt_object_kind(root.hover_info.id.kind)}" : "";
                    }
                }
            }
        }
    }
}
